# Site settings
course_name: Data Structure
course_description: "This is an programming course for students who need a basic understanding of data structure. We will have hands-on exercises and quizzes to help you get familiar with each topic, and students will exercise logical thinking and programming skills for dealing with scientific problems."
course_semester: "Spring 2024"

baseurl: "/nsysu-math208" # the subpath of your site, e.g. /blog/
url: "https://phonchi.github.io/" # the base hostname & protocol for your site

schoolname: "National Sun Yat-Sen University"
schoolurl: "https://www.nsysu.edu.tw/"
#twitter_username: username 

address: |
    No.70 Lien-hai Rd., Kaohsiung 80424, 
    Taiwan

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
